name: Docker Publish

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository
      packages: write # Needed to push packages to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Use the GitHub username running the action
          password: ${{ secrets.GHCR_PAT }} # Use the PAT stored as a secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Build context is the root of the repository
          push: true # Push the image after building
          tags: ghcr.io/${{ lower(github.repository_owner) }}/${{ github.event.repository.name }}:latest
          # You can add more tags here, e.g., based on commit SHA or Git tags
          # tags: |
          #   ghcr.io/${{ lower(github.repository_owner) }}/${{ lower(github.event.repository.name) }}:latest
          #   ghcr.io/${{ lower(github.repository_owner) }}/${{ lower(github.event.repository.name) }}:${{ github.sha }} 